services:
  # バックエンド (FastAPI) サービス
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/workspaces/test-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:password@db:3306/mydatabase
    depends_on:
      - db
    tty: true

  # フロントエンド (React) サービス
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # ソースコードをマウントし、node_modulesはコンテナ内のものを使用
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # ホットリロードを有効にするため
    stdin_open: true
    tty: true

  # データベース (MySQL) サービス
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

# データ永続化のための名前付きボリューム
volumes:
  mysql-data: